Traceback (most recent call last):
  File "./dynfd.py", line 71, in <module>
    daemon.start()
  File "/usr/local/lib/python2.7/dist-packages/DNF/daemon.py", line 85, in start
    self.run()
  File "./dynfd.py", line 16, in run
    self.rm_limit()
  File "./dynfd.py", line 62, in rm_limit
    Firewall().rm_all_limit()
  File "/usr/local/lib/python2.7/dist-packages/DNF/firewall/df_firewall.py", line 110, in rm_all_limit
    Data().rm_all_limit()
  File "/usr/local/lib/python2.7/dist-packages/DNF/database/df_data.py", line 176, in rm_all_limit
    self.db.alter(sql)
  File "/usr/local/lib/python2.7/dist-packages/DNF/database/storage.py", line 28, in alter
    self.cur.execute(sql)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "./dynfd.py", line 71, in <module>
    daemon.start()
  File "/usr/local/lib/python2.7/dist-packages/DNF/daemon.py", line 85, in start
    self.run()
  File "./dynfd.py", line 18, in run
    self.update_stats()
  File "./dynfd.py", line 27, in update_stats
    clients = D.get_all_active_clients()
  File "/usr/local/lib/python2.7/dist-packages/DNF/database/df_data.py", line 20, in get_all_active_clients
    return self.db.get_all_rows(sql)
  File "/usr/local/lib/python2.7/dist-packages/DNF/database/storage.py", line 24, in get_all_rows
    self.cur.execute(sql)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "./dynfd.py", line 70, in <module>
    daemon.start()
  File "/usr/local/lib/python2.7/dist-packages/DNF/daemon.py", line 85, in start
    self.run()
  File "./dynfd.py", line 18, in run
    self.update_stats()
  File "./dynfd.py", line 26, in update_stats
    clients = Data().get_all_active_clients()
  File "/usr/local/lib/python2.7/dist-packages/DNF/database/df_data.py", line 20, in get_all_active_clients
    return self.db.get_all_rows(sql)
  File "/usr/local/lib/python2.7/dist-packages/DNF/database/storage.py", line 24, in get_all_rows
    self.cur.execute(sql)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "./dynfd.py", line 70, in <module>
    daemon.start()
  File "/usr/local/lib/python2.7/dist-packages/DNF/daemon.py", line 85, in start
    self.run()
  File "./dynfd.py", line 18, in run
    self.update_stats()
  File "./dynfd.py", line 26, in update_stats
    clients = Data().get_all_active_clients()
  File "/usr/local/lib/python2.7/dist-packages/DNF/database/df_data.py", line 20, in get_all_active_clients
    return self.db.get_all_rows(sql)
  File "/usr/local/lib/python2.7/dist-packages/DNF/database/storage.py", line 24, in get_all_rows
    self.cur.execute(sql)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
/usr/bin/python: can't find '__main__' module in '/opt/DF/init.d'
